### ISSUE TITLE
Points markers

### ISSUE THREAD

**Issue by alangularte** [markmarkoh/datamaps#101]
Hi!

Is it possible to insert points markers (latitude/longitude) like Google Maps?

**Comment by twodayslate** [comment]
Sorry for bringing up an old issue but I thought this was relevant here. 

An actual pin marker does not scale with the map. I've been trying to get everything else to zoom except the markers but I have not had any luck. 

I've tried not running 'scale' in the redraw function (using `g:not(.pins)`) but it needs the scale otherwise the spacing isn't correct.


Perhaps I'm not thinking about this problem in the correct way.
