### ISSUE TITLE
Why is Russia appearing to the left side near US?

### ISSUE THREAD

**Issue by maeishoj** [markmarkoh/datamaps#153]
Is it possible to prevent this from happening? I would like something that looks like this:

http://jvectormap.com/maps/world/world/

And no i don't want to use jvectormap.

**Comment by markmarkoh** [comment]
Unfortunately that's just the way d3's projections work. Since that part of Russia is technically in that hemisphere, it renders that way.

I can't think of any way off the top of my head to stop that from happening. I looked around at some custom D3 projections but I don't see any support there either.

**Comment by hugomosh** [comment]
+1

What about changing the point data.
