### ISSUE TITLE
Json object instead of an external JSON file for custom map json

### ISSUE THREAD

**Issue by adrianbj** [markmarkoh/datamaps#200]
Just wondering if you'd be interested / willing to support using a json object directly, rather than needing to point to a json file?

**Comment by markmarkoh** [comment]
@adrianbj Yes, I think that'd be great.

I think there should be a property that can accept a function an object. The object would need to be TopoJSON, but the function should be able to return JSON directly or return a Promise (or take a callback).

Let's call it `mapTopoJson` for right now:

These cases should work:
```js
mapTopoJson: function(callback) {
   callback(window.alreadyLoadedCustomTopoJson);
}
```
-----
```js
mapTopoJson: window.alreadyLoadedCustomTopoJson
```
----
```js
mapTopoJson: function(callback) {
  $.get('/myurlfortopojson').then(function(data) {
    callback(data);
  });
}
```

Internally, datamaps would check the type of `mapTopoJson` to determine what logic to use.

Then, in the case that there is a set `dataUrl` but no `mapTopoJson` function, we would convert that to:
```js
if ( typeof dataUrl === "string" && !mapTopoJson ) {
  mapTopoJson = function(callback) {
    d3.json(dataUrl, callback)
  }
}
```

Does that make sense? Still thinking it over, but overall I encourage the ability to do this without an AJAX call (rather, be less prescriptive on how it's done, since currently it just calls `d3.json` which might not work, especially if you had to `POST` it or something.

**Comment by markmarkoh** [comment]
Still thinking through the use case of a `Promise`, since that would be slick. Browser support isn't fully there, so we'd need to work around it, or maybe locally polyfill it. DataMaps doesn't have deps aside from D3 and TopoJSON, so we can't just assume jQuery is available.

**Comment by adrianbj** [comment]
@markmarkoh - thanks for the enthusiasm on this, although I just discovered that what I wanted is actually already implemented using: `dataJson` with this PR: https://github.com/markmarkoh/datamaps/pull/121

I am using it now and works exactly as I need.

I am using angular and https://github.com/dmachat/angular-datamaps so I am taking care of the ajax and promise using $http provider so my needs are covered, but it would be cool to have this built into datamaps without any dependencies.

**Comment by Downchuck** [comment]
@markmarkoh On this note: I am looking to have a drill-down feature, where the user can click a US state, then that state becomes the map, and the county-data is subsequently used from topojson.

I am thinking something like onclick(geometry) { map.options.geographyConfig.dataJson = [geometry] } might work, so I'm giving that a go in the code.
