### ISSUE TITLE
How can i use only one map of specific country?

### ISSUE THREAD

**Issue by gnumoksha** [markmarkoh/datamaps#281]
When i include "dist/datamaps.bra.js" i received the error:
TypeError: data.objects is undefined

**Comment by markmarkoh** [comment]
@gnumoksha 'bra' needs to be set as the scope manually, and a custom projection needs to be applied to zoom into the right area (otherwise it appears very small):

Example: http://jsbin.com/mukaderale/edit?html,js,output

![screenshot 2016-03-21 11 15 20](https://cloud.githubusercontent.com/assets/11268/13925407/3117120a-ef56-11e5-805a-0586e692a8e9.png)

**Comment by gnumoksha** [comment]
Thank you very much!

**Comment by shobuz03** [comment]
I cann't generate bangladesh topo json
