### ISSUE TITLE
Wrong arc extremities using country codes

### ISSUE THREAD

**Issue by magic890** [markmarkoh/datamaps#295]
Using country codes to draw arcs, will trigger strange behaviours due to the implementation of that feature using centroids.

In fact drawing an arc from Russia (or wherever) to USA, will result in an arc landing to Canada.
<img width="1152" alt="screen shot 2016-05-05 at 17 13 13" src="https://cloud.githubusercontent.com/assets/1352670/15047380/fe74b728-12e4-11e6-8078-bd0bbd702e82.png">

Code:
```
map.arc([
  {
    origin: 'RUS',
    destination: 'USA'
  }
]);
```

Functionality implementation using centroid (https://github.com/markmarkoh/datamaps/blob/master/src/js/datamaps.js#L378 and https://github.com/markmarkoh/datamaps/blob/master/src/js/datamaps.js#L384):
> ... = self.path.centroid(svg.select('path.' + datum.origin).data()[0])

[Calculation of centroid](https://en.wikipedia.org/wiki/Centroid) in an L object (e.g. USA state distribution can be contained inside an L shape object) can results in a centroid placed outside the object area.

I think that a more robust way to implement arcs between countries can be add to world topojson capitals coordinates and draw arcs between them. 

@markmarkoh what are your feedback?

**Comment by markmarkoh** [comment]
This one is definitely tricky since we are using the geometric `centroid` to determine where the center of the geography, so clearly it falls apart for USA especially with Alaska being so far out of the way.

We could make a list of known irregular countries, like USA and maybe CAN, and handle those special cases within the library. Like `if (arc.center == "USA") { return [-97, 33] }` (or better yet in a switch statement that falls through to the geometric `centroid` call it currently uses.

Or we can predetermine the centers of each country in the topojson. That makes it a bit hard to add new topojson files.

@magic890 thoughts?
